name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Greetings, thanks for pointing out the issue, I will be working on it"
        pr-message: "Welcome, YOUR FIRST PULL request, contribution is appreciated"
